service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60
  stage: dev
  region: us-west-2
  environment:
    foo: 123

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: '/api'
          method: get
          cors: true
      - http:
          path: '/api'
          method: post
          cors: true
      - http:
          path: '/api'
          method: put
          cors: true

custom:
  serverless-offline:	
    httpPort: 4000